name: Installing Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-14]
        py-version: ["3.10","3.11","3.12"]
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py-version }}
    - name: Output Py Vesrion
      run: python3 --version
        
